import { Supplier, MaterialItem, MaterialCategory, SupplyRegion, AISearchResult } from "./types.js";

// Hardcoded state of key building material suppliers in Nigeria
export const NIGERIAN_SUPPLIERS: Supplier[] = [
  {
    id: "sup-lag-01",
    name: "Coker Allied Merchants Ltd",
    marketName: "Coker Building Materials Market, Orile",
    city: "Lagos",
    state: "Lagos",
    contactPhone: "+234 803 111 2233",
    rating: 4.8,
    isVerified: true,
    apiConnected: true,
    apiLatencyMs: 78,
  },
  {
    id: "sup-lag-02",
    name: "Alaba Premium Steel & Co",
    marketName: "Alaba International Market, Ojo",
    city: "Lagos",
    state: "Lagos",
    contactPhone: "+234 812 444 5566",
    rating: 4.5,
    isVerified: true,
    apiConnected: true,
    apiLatencyMs: 142,
  },
  {
    id: "sup-lag-03",
    name: "Lekki block & Sand Depot",
    marketName: "Jakande Blockmaking Yard & Quarry Hub",
    city: "Lekki Phase 2",
    state: "Lagos",
    contactPhone: "+234 809 333 4455",
    rating: 4.2,
    isVerified: false,
    apiConnected: true,
    apiLatencyMs: 95,
  },
  {
    id: "sup-abj-01",
    name: "Dei-Dei Mega Builders Depot",
    marketName: "Dei-Dei Building Materials Market, Gwagwa",
    city: "Abuja",
    state: "Abuja",
    contactPhone: "+234 806 777 8899",
    rating: 4.9,
    isVerified: true,
    apiConnected: true,
    apiLatencyMs: 110,
  },
  {
    id: "sup-abj-02",
    name: "Kugbo Wood & Timber Hub",
    marketName: "Kugbo Timber & Roofing Association",
    city: "Abuja",
    state: "Abuja",
    contactPhone: "+234 818 999 0011",
    rating: 4.4,
    isVerified: true,
    apiConnected: true,
    apiLatencyMs: 185,
  },
  {
    id: "sup-ph-01",
    name: "Mile 3 Construction Syndicate",
    marketName: "Mile 3 Building Supplies, Diobu",
    city: "Port Harcourt",
    state: "Port Harcourt",
    contactPhone: "+234 703 555 6677",
    rating: 4.7,
    isVerified: true,
    apiConnected: true,
    apiLatencyMs: 124,
  },
  {
    id: "sup-ph-02",
    name: "Iloabuchi Timber Dealers",
    marketName: "Iloabuchi Wood Market, Mile 2 Diobu",
    city: "Port Harcourt",
    state: "Port Harcourt",
    contactPhone: "+234 814 123 4567",
    rating: 4.1,
    isVerified: false,
    apiConnected: false,
    apiLatencyMs: 0,
  },
  {
    id: "sup-kan-01",
    name: "Sabon Gari Iron & Block Merchant",
    marketName: "Sabon Gari Building Materials Hub",
    city: "Kano",
    state: "Kano",
    contactPhone: "+234 802 888 1122",
    rating: 4.6,
    isVerified: true,
    apiConnected: true,
    apiLatencyMs: 201,
  },
  {
    id: "sup-iba-01",
    name: "Oyo State Steel & Aggregate Hub",
    marketName: "Express Road Block Makers, Challenge",
    city: "Ibadan",
    state: "Ibadan",
    contactPhone: "+234 805 777 4488",
    rating: 4.3,
    isVerified: true,
    apiConnected: true,
    apiLatencyMs: 112,
  }
];

export const INITIAL_MATERIALS: MaterialItem[] = [
  // CEMENT & BINDERS
  {
    id: "mat-cem-01",
    name: "Dangote Cement 3X (Grade 42.5R)",
    category: MaterialCategory.CEMENT_BINDERS,
    price: 7850,
    unit: "50kg Bag",
    brand: "Dangote",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 1450,
    lastVerified: new Date().toISOString(),
    specifications: "High strength multi-purpose portal cement with rapid hardening",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-cem-02",
    name: "BUA Cement 50kg (King Size)",
    category: MaterialCategory.CEMENT_BINDERS,
    price: 7700,
    unit: "50kg Bag",
    brand: "BUA",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 890,
    lastVerified: new Date().toISOString(),
    specifications: "Premium quality concrete grade binder, works beautifully with sharp sand",
    isLiveStockSynced: true,
    priceTrend: "down",
  },
  {
    id: "mat-cem-03",
    name: "Lafarge Elephant Cement (Classic 32.5N)",
    category: MaterialCategory.CEMENT_BINDERS,
    price: 7550,
    unit: "50kg Bag",
    brand: "Lafarge",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 620,
    lastVerified: new Date().toISOString(),
    specifications: "Ideal for plastering, tiling and minor block casting projects",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-cem-04",
    name: "Dangote Cement 3X (Grade 42.5R) - Abuja Standard",
    category: MaterialCategory.CEMENT_BINDERS,
    price: 8200,
    unit: "50kg Bag",
    brand: "Dangote",
    supplierId: "sup-abj-01",
    supplierName: "Dei-Dei Mega Builders Depot",
    supplierCity: "Abuja",
    supplierState: "Abuja",
    stockLevel: 2500,
    lastVerified: new Date().toISOString(),
    specifications: "Premium grade portland cement. Price inclusive of Dei-Dei market levies",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-cem-05",
    name: "BUA Cement 50kg - Kano Hub",
    category: MaterialCategory.CEMENT_BINDERS,
    price: 8100,
    unit: "50kg Bag",
    brand: "BUA",
    supplierId: "sup-kan-01",
    supplierName: "Sabon Gari Iron & Block Merchant",
    supplierCity: "Kano",
    supplierState: "Kano",
    stockLevel: 410,
    lastVerified: new Date().toISOString(),
    specifications: "King size packaging, ideal for high-heat arid settings in North Nigeria",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-cem-06",
    name: "Dangote Cement 3X - PH Distribution",
    category: MaterialCategory.CEMENT_BINDERS,
    price: 8400,
    unit: "50kg Bag",
    brand: "Dangote",
    supplierId: "sup-ph-01",
    supplierName: "Mile 3 Construction Syndicate",
    supplierCity: "Port Harcourt",
    supplierState: "Port Harcourt",
    stockLevel: 1100,
    lastVerified: new Date().toISOString(),
    specifications: "Standard grade for damp-resistance in coastal foundations",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },

  // STEEL & REBARS
  {
    id: "mat-st-01",
    name: "16mm TMT High-Yield Iron Rods (Length 12m)",
    category: MaterialCategory.STEEL_REBARS,
    price: 13500,
    unit: "Length (12m)",
    brand: "Tiger TMT",
    supplierId: "sup-lag-02",
    supplierName: "Alaba Premium Steel & Co",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 1500,
    lastVerified: new Date().toISOString(),
    specifications: "High-ductility steel reinforcement rods for beams and pillars",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-st-02",
    name: "12mm High-Tension Ribbed Iron Rods",
    category: MaterialCategory.STEEL_REBARS,
    price: 8300,
    unit: "Length (12m)",
    brand: "Mayor Steel",
    supplierId: "sup-lag-02",
    supplierName: "Alaba Premium Steel & Co",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 2200,
    lastVerified: new Date().toISOString(),
    specifications: "Standard residential slab reinforcement rebars",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-st-03",
    name: "10mm Ribbed Structural Rebars",
    category: MaterialCategory.STEEL_REBARS,
    price: 5900,
    unit: "Length (12m)",
    brand: "Tiger TMT",
    supplierId: "sup-lag-02",
    supplierName: "Alaba Premium Steel & Co",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 1800,
    lastVerified: new Date().toISOString(),
    specifications: "Ideal for ring beams and lintel binding ties",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-st-04",
    name: "16mm TMT Reinforcement Rods - Ton Pack",
    category: MaterialCategory.STEEL_REBARS,
    price: 1320000,
    unit: "Ton",
    brand: "Tiger TMT",
    supplierId: "sup-lag-02",
    supplierName: "Alaba Premium Steel & Co",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 22,
    lastVerified: new Date().toISOString(),
    specifications: "Bulk unit (approx 74 lengths per ton of 16mm rods)",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-st-05",
    name: "16mm TMT High-Yield Iron Rods - Abuja",
    category: MaterialCategory.STEEL_REBARS,
    price: 14200,
    unit: "Length (12m)",
    brand: "Tiger TMT",
    supplierId: "sup-abj-01",
    supplierName: "Dei-Dei Mega Builders Depot",
    supplierCity: "Abuja",
    supplierState: "Abuja",
    stockLevel: 940,
    lastVerified: new Date().toISOString(),
    specifications: "High strength rebars compliant with SON structural standards",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },

  // ROOFING & CEILINGS
  {
    id: "mat-rf-01",
    name: "Aluminum Longspan Roofing Sheets (0.45mm)",
    category: MaterialCategory.ROOFING_CEILING,
    price: 5800,
    unit: "Square Meter (SQM)",
    brand: "Tower Aluminum",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 3200,
    lastVerified: new Date().toISOString(),
    specifications: "Rust-free 0.45mm thickness aluminum sheeting, variety of colors",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-rf-02",
    name: "Gerard Stone Coated Roof Tiles (Classic Maroon)",
    category: MaterialCategory.ROOFING_CEILING,
    price: 9400,
    unit: "Square Meter (SQM)",
    brand: "Gerard",
    supplierId: "sup-abj-02",
    supplierName: "Kugbo Wood & Timber Hub",
    supplierCity: "Abuja",
    supplierState: "Abuja",
    stockLevel: 450,
    lastVerified: new Date().toISOString(),
    specifications: "New Zealand imported stone-chip coated premium steel tile sheets",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },

  // BLOCKS & AGGREGATES
  {
    id: "mat-bl-01",
    name: "9-Inch Vibrated Hollow Block",
    category: MaterialCategory.BLOCKS_AGGREGATES,
    price: 750,
    unit: "Piece",
    brand: "Coker Casts",
    supplierId: "sup-lag-03",
    supplierName: "Lekki block & Sand Depot",
    supplierCity: "Lekki Phase 2",
    supplierState: "Lagos",
    stockLevel: 3500,
    lastVerified: new Date().toISOString(),
    specifications: "Machine-vibrated 9x9x18 hollow concrete block, load-bearing standard",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-bl-02",
    name: "6-Inch Vibrated Hollow Block",
    category: MaterialCategory.BLOCKS_AGGREGATES,
    price: 630,
    unit: "Piece",
    brand: "Coker Casts",
    supplierId: "sup-lag-03",
    supplierName: "Lekki block & Sand Depot",
    supplierCity: "Lekki Phase 2",
    supplierState: "Lagos",
    stockLevel: 4200,
    lastVerified: new Date().toISOString(),
    specifications: "Standard 6x9x18 partitioning concrete masonry blocks",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-bl-03",
    name: "Sharp Sand Tipper Truck (20 Tons)",
    category: MaterialCategory.BLOCKS_AGGREGATES,
    price: 135000,
    unit: "Tipper Truck (20t)",
    brand: "Ogun Quarry",
    supplierId: "sup-lag-03",
    supplierName: "Lekki block & Sand Depot",
    supplierCity: "Lekki Phase 2",
    supplierState: "Lagos",
    stockLevel: 15,
    lastVerified: new Date().toISOString(),
    specifications: "Washed coarse sharp sand for casting, foundation fillings & decking",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-bl-04",
    name: "Granite Stone (3/4 Inch, 20 Tons)",
    category: MaterialCategory.BLOCKS_AGGREGATES,
    price: 275000,
    unit: "Tipper Truck (20t)",
    brand: "Abeokuta Granite",
    supplierId: "sup-lag-03",
    supplierName: "Lekki block & Sand Depot",
    supplierCity: "Lekki Phase 2",
    supplierState: "Lagos",
    stockLevel: 8,
    lastVerified: new Date().toISOString(),
    specifications: "High crushing strength granite gravel, sized precisely 19mm - 20mm",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-bl-05",
    name: "9-Inch Hollow Block - Abuja Castings",
    category: MaterialCategory.BLOCKS_AGGREGATES,
    price: 800,
    unit: "Piece",
    brand: "Dei-Dei Casts",
    supplierId: "sup-abj-01",
    supplierName: "Dei-Dei Mega Builders Depot",
    supplierCity: "Abuja",
    supplierState: "Abuja",
    stockLevel: 1900,
    lastVerified: new Date().toISOString(),
    specifications: "Double Core, machine vibrated load-bearing sandcrete blocks",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },

  // PAINT & FINISHING / ELECTRICAL / PLUMBING
  {
    id: "mat-el-01",
    name: "Coleman Cable 1.5mm Single Core Copper Wire (100m)",
    category: MaterialCategory.ELECTRICAL_WIRING,
    price: 34500,
    unit: "Roll (100m)",
    brand: "Coleman Cables",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 420,
    lastVerified: new Date().toISOString(),
    specifications: "Pure insulated copper wiring, SON and ISO certified for light circuits",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-el-02",
    name: "Coleman Cable 2.5mm Single Core Copper Wire (100m)",
    category: MaterialCategory.ELECTRICAL_WIRING,
    price: 52000,
    unit: "Roll (100m)",
    brand: "Coleman Cables",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 310,
    lastVerified: new Date().toISOString(),
    specifications: "High capacity copper routing for power sockets/AC wiring",
    isLiveStockSynced: true,
    priceTrend: "up",
  },
  {
    id: "mat-pl-01",
    name: "20mm PPR Hot & Cold Water Pipes (Length 4m)",
    category: MaterialCategory.PLUMBING_SANETARY,
    price: 4900,
    unit: "Length (4m)",
    brand: "Vesbo",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 550,
    lastVerified: new Date().toISOString(),
    specifications: "High pressure polymer plumbing pipes, fusable joins",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-tl-01",
    name: "Royal Porcelain Floor Tiles 60cm x 60cm (Box)",
    category: MaterialCategory.TILES_FINISHING,
    price: 9800,
    unit: "Box (1.44 SQM)",
    brand: "Royal Tiles",
    supplierId: "sup-lag-01",
    supplierName: "Coker Allied Merchants Ltd",
    supplierCity: "Lagos",
    supplierState: "Lagos",
    stockLevel: 380,
    lastVerified: new Date().toISOString(),
    specifications: "Vitrified high gloss floor porcelain, elegant marble vein texture",
    isLiveStockSynced: true,
    priceTrend: "down",
  },

  // WOOD & TIMBER
  {
    id: "mat-wd-01",
    name: "2 inch x 3 inch Obeche Timber Joists",
    category: MaterialCategory.WOOD_TIMBER,
    price: 2400,
    unit: "Length (12ft)",
    brand: "Ondo Timber",
    supplierId: "sup-abj-02",
    supplierName: "Kugbo Wood & Timber Hub",
    supplierCity: "Abuja",
    supplierState: "Abuja",
    stockLevel: 980,
    lastVerified: new Date().toISOString(),
    specifications: "Kiln-dried Obeche hardwood framing planks for roofing/ceilings",
    isLiveStockSynced: true,
    priceTrend: "stable",
  },
  {
    id: "mat-wd-02",
    name: "Marine Scaffold Plywood (8ft x 4ft x 18mm)",
    category: MaterialCategory.WOOD_TIMBER,
    price: 36000,
    unit: "Sheet",
    brand: "Sapele Plywood",
    supplierId: "sup-abj-02",
    supplierName: "Kugbo Wood & Timber Hub",
    supplierCity: "Abuja",
    supplierState: "Abuja",
    stockLevel: 210,
    lastVerified: new Date().toISOString(),
    specifications: "Waterproof marine plywood sheet for concrete decking formwork",
    isLiveStockSynced: true,
    priceTrend: "up",
  }
];

// Helper to simulate calling real-time API stock checkers
export function queryLiveStockSuppliers(
  searchQuery?: string,
  region?: SupplyRegion,
  category?: MaterialCategory
) {
  let materials = [...INITIAL_MATERIALS];

  // Apply basic filters
  if (region) {
    materials = materials.filter(m => m.supplierState.toLowerCase() === region.toLowerCase());
  }
  if (category) {
    materials = materials.filter(m => m.category === category);
  }
  if (searchQuery) {
    const q = searchQuery.toLowerCase();
    materials = materials.filter(m => 
      m.name.toLowerCase().includes(q) || 
      m.brand.toLowerCase().includes(q) ||
      m.specifications.toLowerCase().includes(q)
    );
  }

  // Simulate calling the mock distributed inventory API for each supplier
  const apiLogs = NIGERIAN_SUPPLIERS.map(sup => {
    // If region filter is set and supplier is in different region, skip API test logs
    if (region && sup.state.toLowerCase() !== region.toLowerCase()) {
      return null;
    }

    const matchingInStock = materials.filter(m => m.supplierId === sup.id);
    const mockLatency = sup.apiConnected ? sup.apiLatencyMs + Math.floor(Math.random() * 30 - 15) : 0;
    
    return {
      supplierId: sup.id,
      supplierName: sup.name,
      status: !sup.apiConnected ? "offline" : mockLatency > 180 ? "slow" : "success",
      latencyMs: mockLatency,
      stockFound: matchingInStock.reduce((acc, current) => acc + current.stockLevel, 0)
    };
  }).filter(log => log !== null) as AISearchResult["simulatedApiLogs"];

  // Introduce minor real-time pricing and stock fluctuations to simulate live updates (+/- 1.5% and randomly reduce/boost stock)
  const modifiedMaterials = materials.map(item => {
    const matchedSupplier = NIGERIAN_SUPPLIERS.find(s => s.id === item.supplierId);
    const fluctuationPercent = (Math.sin(Date.now() + item.id.charCodeAt(0)) * 1.5) / 100; // deterministic fluctuation based on ID and current time
    const adjustedPrice = Math.round(item.price * (1 + fluctuationPercent));
    
    // Slight stock draft
    const timeBasedOffset = Math.floor(Math.sin((Date.now() / 100000) + item.id.charCodeAt(1)) * 10);
    const adjustedStock = Math.max(0, item.stockLevel + timeBasedOffset);

    return {
      ...item,
      price: adjustedPrice,
      stockLevel: adjustedStock,
      isLiveStockSynced: matchedSupplier ? matchedSupplier.apiConnected : false,
      lastVerified: new Date().toISOString()
    };
  });

  return {
    materials: modifiedMaterials,
    apiLogs
  };
}
